In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = 'all'


In [81]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [2]:
1 + 2

3

In [3]:
(1 + 2 * 3 - 4) / 5

0.6

In [4]:
2**8

256

In [5]:
x = 1
y = 1 / 3
x + y

1.3333333333333333

In [6]:
Data_1 = 1 / 5
Data_2 = 3 / 5
Data_1 + Data_2

0.8

In [7]:
type(100)

int

In [8]:
type(100.1)

float

In [9]:
x = 100
type(x)

int

In [10]:
x = 100.1
type(x)

float

In [11]:
x = 'learning'
type(x)

str

In [12]:
x = 1 / 3
x
y = 2 / 3
y

0.3333333333333333

0.6666666666666666

In [13]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


In [14]:
print('x= ' + str(x))

x= 0.3333333333333333


In [15]:
print('weight = {} kg'.format(x))

weight = 0.3333333333333333 kg


In [16]:
x = 1 / 3
y = 1 / 7
z = 1 / 4
print('weight: {0} kg, {1} kg, {2} kg'.format(x, y, z))

weight: 0.3333333333333333 kg, 0.14285714285714285 kg, 0.25 kg


In [17]:
print('weight: {0:.2f} kg, {1:.2f} kg, {2:.2f} kg'.format(x, y, z))

weight: 0.33 kg, 0.14 kg, 0.25 kg


In [18]:
x = [1, 1, 2, 3, 5] # list的定义
print(x) # 显示

[1, 1, 2, 3, 5]


In [19]:
x[0]

1

In [20]:
x[2]

2

In [21]:
print(type(x))
print(type(x[0]))

<class 'list'>
<class 'int'>


In [22]:
s = ['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [23]:
x = [1, 1, 2, 3, 5]
x[3] = 100
print(x)

[1, 1, 2, 100, 5]


In [24]:
x = [1, 1, 2, 3, 5]
len(x)

5

In [25]:
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [26]:
a = [[1, 2, 3], [4, 5, 6]]
print(a[0][1])

2


In [27]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])

5 6 7 8 9


In [28]:
print(y)

range(5, 10)


In [29]:
z = list(range(5, 10))
print(z)

[5, 6, 7, 8, 9]


In [30]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
a = (1, 2, 3)

print(a)

(1, 2, 3)


In [32]:
a[1]

2

In [33]:
type(a)

tuple

In [34]:
a = (1)
type(a)

int

In [35]:
a = (1,)
type(a)

tuple

In [36]:
x = 11
if x > 10:
    print('x is ')                   # ... (A1)
    print('　　　　larger than 10.') # ... (A2)
else:
    print('x is smaller than 11')    # ... (B1)

x is 
　　　　larger than 10.


In [37]:
x > 10

True

In [38]:
type(x > 10)

bool

In [39]:
x = 15
if 10 < x and x < 20:
    print('x is between 10 and 20.')

x is between 10 and 20.


In [40]:
for i in [1, 2, 3]:
    print(i)

1
2
3


In [41]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)): # len(num) 是 num 的元素数
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


In [42]:
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num):
    num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


In [43]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [44]:
import numpy as np

In [45]:
x = np.array([1, 2])
x

array([1, 2])

In [46]:
print(x)

[1 2]


In [47]:
x = np.array([1, 2])
y = np.array([3, 4])
print(x + y)

[4 6]


In [48]:
type(x)

numpy.ndarray

In [49]:
x = np.array([1, 2])
print(x[0])

1


In [50]:
x = np.array([1, 2])
x[0] = 100
print(x)

[100   2]


In [51]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [52]:
print(np.arange(5, 10))

[5 6 7 8 9]


In [53]:
a = np.array([1, 1])
b = a
print('a =' + str(a))
print('b =' + str(b))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

a =[1 1]
b =[1 1]
b =[100   1]
a =[100   1]


In [54]:
a = np.array([1, 1])
b = a.copy()
print('a =' + str(a))
print('b =' + str(b))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

a =[1 1]
b =[1 1]
b =[100   1]
a =[1 1]


In [55]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [56]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

In [57]:
h, w = x.shape
print(h)
print(w)

2
3


In [58]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2]

6

In [59]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


In [60]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [61]:
x = np.zeros((2, 10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [61]:
x = np.ones((2, 10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [62]:
np.random.rand(2, 3)

array([[0.09770096, 0.53849669, 0.73969449],
       [0.4877997 , 0.13745162, 0.6153994 ]])

In [69]:
a = np.arange(-10,9+1,1)
print(a)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


In [68]:
a = a.reshape(4, 5)
print(a)

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]


In [70]:
np.array([[4, 4, 4], [8, 8, 8]])


array([[4, 4, 4],
       [8, 8, 8]])

In [65]:
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


In [66]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


In [67]:
x = np.array([[4, 4, 4], [9, 9, 9]])
print(np.sqrt(x))

[[2. 2. 2.]
 [3. 3. 3.]]


In [68]:
v = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[1, 1], [2, 2], [3, 3]])
print(v.dot(w))

[[14 14]
 [32 32]]


In [69]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [70]:
print(x[5:])

[5 6 7 8 9]


In [71]:
print(x[3:8])

[3 4 5 6 7]


In [72]:
print(x[3:8:2])

[3 5 7]


In [73]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [74]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
print(y[:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


In [75]:
x = np.array([1, 1, 2, 3, 5, 8, 13])
x > 3

array([False, False, False, False,  True,  True,  True])

In [76]:
x[x > 3]

array([ 5,  8, 13])

In [77]:
x[x > 3] = 999
print(x)

[  1   1   2   3 999 999 999]


In [78]:
import numpy as np
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [79]:
def my_func1():
    print('Hi!')
# 函数 my_func1() 的定义到此为止 
my_func1() # 运行函数

Hi!


In [80]:
def my_func2(a, b):
    c = a + b
    return c

my_func2(1, 2)

3

In [81]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s

In [82]:
data = np.random.randn(100)
data_mean, data_std = my_func3(data)
print('mean:{0:.2f}, std:{1:.2f}'.format(data_mean, data_std))

mean:0.29, std:1.03


In [83]:
output = my_func3(data)
print(output)
print(type(output))
print('mean:{0:.2f}, std:{1:.2f}'.format(output[0], output[1]))

(0.28767675929489345, 1.0341182306932364)
<class 'tuple'>
mean:0.29, std:1.03


In [84]:
data = np.array([1, 1, 2, 3, 5, 8, 13])
print(data)

np.save('datafile.npy', data)  # 保存文件 
data = []                      # 清空数据
print(data)

data = np.load('datafile.npy') # 读取文件
print(data)

[ 1  1  2  3  5  8 13]
[]
[ 1  1  2  3  5  8 13]


In [85]:
data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])
np.savez('datafile2.npz', data1=data1, data2=data2) # 保存文件
data1 = [] # 清空数据
data2 = []
outfile = np.load('datafile2.npz') # 读取文件
print(outfile.files) # 显示存储的所有数据
data1 = outfile['data1'] # 取出data1
data2 = outfile['data2'] # 取出data2
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
